### ISSUE TITLE
1334px以上のPSDを書き出すとレイアウトが崩れる

### ISSUE THREAD

**Issue by fukusin** [kyubuns/Baum2#11]
RetinaサイズのPSDでハマったので共有されてもらいます。

Baum.jsでPSDの解像度が1334pxで制限されているようです。
Baum.maxLengthをPSDサイズ以上にすると直りました。
Readmeを見落としていたらすみません。

それ以外は、まさに探していた機能です。素晴らしい！！

**Comment by kyubuns** [comment]
READMEに書き漏れてますが、おっしゃるとおり1334px超えのpsdは1334pxにリサイズされます。
psdはでかく作っておいて、後から（容量などの都合で）サイズ変更できるようにこのような実装になっているので、
Baum.jsのmaxLengthを好きなサイズに変更してお使いください。

READMEに記述するまで、このissueはOpenにしておきます。
