### ISSUE TITLE
Not getting button work

### ISSUE THREAD

**Issue by RYG81** [kyubuns/Baum2#3]
Hi, I am trying a little complex UI here.
[t1.zip](https://github.com/kyubuns/Baum2/files/2909896/t1.zip)
I have named layers quiet similar to your layer naming but in my case, I am not getting button script added on button layers.
Can you help?
---------------------------------------------------------------------------------------
Google Translate to Chines - 
Hāi, wǒ zài zhèlǐ chángshì yīxiē fùzá de UI.
[T1.Zip](https://Github.Com/kyubuns/Baum2/files/2909896/t1.Zip)
wǒ yǐjīng jiāng tú céng mìngmíng wèi lèisì yú nín de tú céng mìngmíng, dàn zài wǒ de qíngkuàng xià, wǒ méiyǒu zài ànniǔ tú céng shàng tiānjiā ànniǔ jiǎoběn.
Nǐ néng bāng wǒ ma?

**Comment by kyubuns** [comment]
Sorry for no english readme.
You need change button group name in psd to "~~~Button".
For example "Buttonmake order" -> "MakeOrderButton", the gameobject has Button Component.
<img width="335" alt="8 2019-03-01 00-54-58" src="https://user-images.githubusercontent.com/961165/53579320-b189cf80-3bbc-11e9-8493-a571b3e5fef4.png">
<img width="649" alt="unity 2018 2 20f1 64bit - sample unity - unity - pc mac linux standalone opengl 4 1 2019-03-01 00-57-31" src="https://user-images.githubusercontent.com/961165/53579515-088fa480-3bbd-11e9-8627-15c4b0e6e321.png">

**Comment by RYG81** [comment]
I do have named it but will try again.
Thanks.

**Comment by RYG81** [comment]
It worked and I now understand the basic of it. Will try help you on creating documentation and example PSD and UI files. But will take time.

**Comment by kyubuns** [comment]
Thank you very much!
I'm looking forward to it!

**Comment by RYG81** [comment]
Hi Sorry for opening it again. Can you please work on better import and auto update of content? AS dragging stuff from explorer does not feel good.

**Comment by kyubuns** [comment]
OK, I recommend that you set the output directory (by PhotoshopScript) as import directory.
Now all you need to do is run baum script on Photoshop, reimport on Unity. (You don't need drag on explorer.)
There is one problem. If you run reimport on Unity before complete baum script, fail create prefab.

I think that this is bother too.
I create new issue about this problem. #5

**Comment by RYG81** [comment]
[slider_test.zip](https://github.com/kyubuns/Baum2/files/2926262/slider_test.zip)
Trying to get unity like the slider but it's just regular fill slider. How can we create a slider with head similar to unity UI system? I have attached a file for same to test.

**Comment by kyubuns** [comment]
Sorry, Slider head (called Handle by Unity) is not implemented yet.
I create new issue -> #6
