### ISSUE TITLE
9Slice化をしない指定

### ISSUE THREAD

**Issue by itouh2-i0plus** [kyubuns/Baum2#7]
ImportにあるPNG画像はOnionRingによって､必ず
9スライス画像へと変換されますが
それをさせたくない場合に対応できるように拡張したいと思っています
その場合､どのような方法がよいでしょうか

案1)ファイル名にある文字列がはいっている場合に非9スライス
案2)非9スライス画像リストを読み込む

**Comment by kyubuns** [comment]
レイヤー名に `@Slice=Disable` と書いておくと9Sliceを無効にできる、ということでいかがでしょう。
これはグループ単位では効かず、レイヤー単位で指定しなければならないオプションになります。

**Comment by itouh2-i0plus** [comment]
ご返答ありがとうございます
承知しました　その方向で検討いたします

@SliceオプションをUnity Baum2処理時に判別できるように
layout.txt､Image Elementにオプションを増やす方法になるかと
現時点では考えております

**Comment by kyubuns** [comment]
masterで `@Slice=False` をつけたらスライスされないようになりました。
